<a href="https://colab.research.google.com/github/Ru1chi/Feynn_Labs/blob/main/data_Assessing_and_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


## **Data Analysis Process**
Asking Questions

Data Wrangling

 a. Gathering Data

 - i. CSV files
 - ii. APIs
 - iii. Web Scraping
 - iv. Databases

b. Assessing Data

c. Cleaning Data
Exploratory Data Analysis

Drawing Conclusion

Comunicating Results

**
## Summary of today's session**



*   You have to become Sherlock
*  Will try to create a framework

*  Frameworks may vary
*  List itemThe goal is to give you idea










1.
## **Data Wrangling**
 Data Gathering

Data Accessing

Data Cleaning

## 1b. Data Accessing

In this step, the data is to be understood more deeply. Before implementing methods to clean it, you will definitely need to have a better idea about what the data is about.


## Types of Unclean Data
There are 2 kinds of unclean data

image.png

Dirty Data (Data with Quality issues): Dirty data, also known as low quality data. Low quality data has content issues.

Duplicated data
Missing Data

Corrupt Data

Inaccurate Data

Messy Data (Data with tidiness issues): Messy data, also known as untidy data. Untidy data has structural issues.Tidy data has the following properties:

Each variable forms a column

Each observation forms a row

Each observational unit forms a table

image.png

In [12]:
import pandas as pd
import numpy as np

In [13]:
patient=pd.read_csv("/content/patients.csv")

In [14]:
treatment=pd.read_csv("/content/treatments.csv")

In [15]:
treatment_cut=pd.read_csv("/content/treatments_cut.csv")

In [16]:
adverse=pd.read_csv("/content/adverse_reactions.csv")

In [17]:
#always summarize the data
#always write the column description

## Types of assessment

manual

programmatic

## Steps of assessment

discover

document

In [18]:
import pandas as pd
import numpy as np

In [19]:
with pd.ExcelWriter('clinical_trials.xlsx') as writer:
  patient.to_excel(writer,sheet_name='patients',index=False)
  treatment.to_excel(writer,sheet_name='treatment',index=False)
  treatment_cut.to_excel(writer,sheet_name='treatment_cut',index=False)
  adverse.to_excel(writer,sheet_name='adverse',index=False)

### Issues with the dataset


**dirty data**  
1.patient id 9 has misspelled his name(patient)

2.state columns sometimes contain full name or abbriviation(patient)

2.name is lower but in parient table is capitalize(treatment)

3.there are missing values but actually nan values(treatment)

4.missing values in hba1c col(treatment)

5.name prblm in (adverse)

7. data missing for 12 rows(patient)(address,
city,	state	,zip_code	,country,	contact	)

8.assigned_index,zip,birthdate has other data type

9.duplicate entries by name john doe(patient)

10 duplicate data as joseph day(treatment)

11.o patient has wright 48 pound as min(patient)

12. one patient has height 27 inches(treatment)

13.hb1ac_change the difference of hbiac_start and end is different(treatment)


**messy data**

1.phon and email in one ccolumn(patient)

2.for aurilin and necvodra the stRT and end in one col(treatment)

3.table adverse should nt exist independently(adverse)

4.merge the treatment and treatment_cut dataset

In [20]:
patient.info()#=https://ev-database.org/#group=vehicle-group&rs-pr=10000_100000&rs-er=0_1000&rs-ld=0_1000&rs-ac=2_23&rs-dcfc=0_300&rs-ub=10_200&rs-tw=0_2500&rs-ef=100_350&rs-sa=-1_5&rs-w=1000_3500&rs-c=0_5000&rs-y=2010_2030&s=1&p=28-10

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    503 non-null    int64
 1   assigned_sex  503 non-null    object
 2   given_name    503 non-null    object
 3   surname       503 non-null    object
 4   address       491 non-null    object
 5   city          491 non-null    object
 6   state         491 non-null    object
 7   zip_code      491 non-null    float64
 8   country       491 non-null    object
 9   contact       491 non-null    object
 10  birthdate     503 non-null    object
 11  weight        503 non-null    float64
 12  height        503 non-null    int64
 13  bmi           503 non-null    float64
dtypes: float64(3), int64(2), object(9)
memory usage: 55.1+ KB

In [21]:
patient.isnull().sum()

patient_id       0
assigned_sex     0
given_name       0
surname          0
address         12
city            12
state           12
zip_code        12
country         12
contact         12
birthdate        0
weight           0
height           0
bmi              0
dtype: int64

In [22]:
patient[patient['address'].isnull()]#missing data

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
209,210,female,Lalita,Eldarkhanov,NaN,NaN,NaN,NaN,NaN,NaN,8/14/1950,143.4,62,26.2
219,220,male,Mỹ,Quynh,NaN,NaN,NaN,NaN,NaN,NaN,4/9/1978,237.8,69,35.1
230,231,female,Elisabeth,Knudsen,NaN,NaN,NaN,NaN,NaN,NaN,9/23/1976,165.9,63,29.4
234,235,female,Martina,Tománková,NaN,NaN,NaN,NaN,NaN,NaN,4/7/1936,199.5,65,33.2
242,243,male,John,O'Brian,NaN,NaN,NaN,NaN,NaN,NaN,2/25/1957,205.3,74,26.4
249,250,male,Benjamin,Mehler,NaN,NaN,NaN,NaN,NaN,NaN,10/30/1951,146.5,69,21.6
257,258,male,Jin,Kung,NaN,NaN,NaN,NaN,NaN,NaN,5/17/1995,231.7,69,34.2
264,265,female,Wafiyyah,Asfour,NaN,NaN,NaN,NaN,NaN,NaN,11/3/1989,158.6,63,28.1
269,270,female,Flavia,Fiorentino,NaN,NaN,NaN,NaN,NaN,NaN,10/9/1937,175.2,61,33.1
278,279,female,Generosa,Cabán,NaN,NaN,NaN,NaN,NaN,NaN,12/16/1962,124.3,69,18.4
286,287,male,Lewis,Webb,NaN,NaN,NaN,NaN,NaN,NaN,4/1/1979,155.3,68,23.6
296,297,female,Chỉ,Lâm,NaN,NaN,NaN,NaN,NaN,NaN,5/14/1990,181.1,63,32.1

In [23]:
patient.describe()

       patient_id      zip_code      weight      height         bmi
count  503.000000    491.000000  503.000000  503.000000  503.000000
mean   252.000000  49084.118126  173.434990   66.634195   27.483897
std    145.347859  30265.807442   33.916741    4.411297    5.276438
min      1.000000   1002.000000   48.800000   27.000000   17.100000
25%    126.500000  21920.500000  149.300000   63.000000   23.300000
50%    252.000000  48057.000000  175.300000   67.000000   27.200000
75%    377.500000  75679.000000  199.500000   70.000000   31.750000
max    503.000000  99701.000000  255.900000   79.000000   37.700000

In [24]:
patient[patient['weight']==48.800000]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
210,211,female,Camilla,Zaitseva,4689 Briarhill Lane,Wooster,OH,44691.0,United States,330-202-2145CamillaZaitseva@superrito.com,11/26/1938,48.8,63,19.1

In [25]:
patient[patient['height']==27.000000]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1

In [26]:
treatment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    280 non-null    object
 1   surname       280 non-null    object
 2   auralin       280 non-null    object
 3   novodra       280 non-null    object
 4   hba1c_start   280 non-null    float64
 5   hba1c_end     280 non-null    float64
 6   hba1c_change  171 non-null    float64
dtypes: float64(3), object(4)
memory usage: 15.4+ KB

In [27]:
treatment_cut.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    70 non-null     object
 1   surname       70 non-null     object
 2   auralin       70 non-null     object
 3   novodra       70 non-null     object
 4   hba1c_start   70 non-null     float64
 5   hba1c_end     70 non-null     float64
 6   hba1c_change  42 non-null     float64
dtypes: float64(3), object(4)
memory usage: 4.0+ KB

In [28]:
adverse.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   given_name        34 non-null     object
 1   surname           34 non-null     object
 2   adverse_reaction  34 non-null     object
dtypes: object(3)
memory usage: 944.0+ bytes

In [29]:
patient[patient.duplicated(subset=['given_name','surname'])]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
229,230,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
237,238,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
244,245,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
251,252,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
277,278,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4

In [30]:
treatment[treatment.duplicated()]

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
136,joseph,day,29u - 36u,-,7.7,7.19,NaN

In [31]:
treatment[treatment.duplicated(subset=['given_name','surname'])]

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
136,joseph,day,29u - 36u,-,7.7,7.19,NaN

In [32]:
treatment_cut[treatment_cut.duplicated(subset=['given_name','surname'])]

Empty DataFrame
Columns: [given_name, surname, auralin, novodra, hba1c_start, hba1c_end, hba1c_change]
Index: []

In [33]:
adverse.duplicated().sum()

0

In [34]:
adverse[adverse.duplicated(subset=['given_name','surname'])]

Empty DataFrame
Columns: [given_name, surname, adverse_reaction]
Index: []

In [35]:
treatment.describe()

       hba1c_start   hba1c_end  hba1c_change
count   280.000000  280.000000    171.000000
mean      7.985929    7.589286      0.546023
std       0.568638    0.569672      0.279555
min       7.500000    7.010000      0.200000
25%       7.660000    7.270000      0.340000
50%       7.800000    7.420000      0.380000
75%       7.970000    7.570000      0.920000
max       9.950000    9.580000      0.990000

In [36]:
treatment.sort_values('hba1c_change',na_position='first')

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,NaN
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,NaN
8,saber,ménard,-,54u - 54u,8.08,7.70,NaN
9,asia,woźniak,30u - 36u,-,7.76,7.37,NaN
10,joseph,day,29u - 36u,-,7.70,7.19,NaN
...,...,...,...,...,...,...,...
49,jackson,addison,-,42u - 42u,7.99,7.51,0.98
17,gina,cain,-,36u - 36u,7.88,7.40,0.98
32,laura,ehrlichmann,-,43u - 40u,7.95,7.46,0.99
245,wu,sung,-,47u - 48u,7.61,7.12,0.99
138,giovana,rocha,-,23u - 21u,7.87,7.38,0.99

In [37]:
treatment.sort_values('hba1c_end')

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
39,krisztina,magyar,-,32u - 27u,7.52,7.01,0.51
80,hideki,haraguchi,-,37u - 35u,7.59,7.05,0.54
187,león,reynoso,-,38u - 40u,7.59,7.06,0.53
53,nasser,mansour,-,33u - 31u,7.51,7.06,0.95
86,ananías,enríquez,-,44u - 45u,7.58,7.07,0.51
...,...,...,...,...,...,...,...
192,valur,bjarkason,-,31u - 36u,9.71,9.41,0.30
171,justyna,kowalczyk,24u - 34u,-,9.84,9.44,NaN
75,mackenzie,mckay,-,44u - 43u,9.87,9.48,0.39
81,robert,wagner,43u - 49u,-,9.84,9.52,0.32
166,annie,allen,36u - 42u,-,9.95,9.58,0.37

In [38]:
treatment.sort_values('hba1c_start')

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
270,mika,martinsson,34u - 43u,-,7.50,7.17,0.33
113,kari,laatikainen,39u - 43u,-,7.50,7.11,NaN
126,jowita,wiśniewska,-,22u - 23u,7.50,7.08,0.92
53,nasser,mansour,-,33u - 31u,7.51,7.06,0.95
105,finlay,sheppard,-,31u - 30u,7.51,7.17,0.34
...,...,...,...,...,...,...,...
25,benoît,bonami,-,44u - 43u,9.82,9.40,0.92
171,justyna,kowalczyk,24u - 34u,-,9.84,9.44,NaN
81,robert,wagner,43u - 49u,-,9.84,9.52,0.32
75,mackenzie,mckay,-,44u - 43u,9.87,9.48,0.39
166,annie,allen,36u - 42u,-,9.95,9.58,0.37

##Dirty has 4 types:

completeness-is data missing

validity-is data invalid(negative height,duplicate data)

accuracy-data is valid but not accurate(adult weight=1kg)

consistency-both valid and accurate but written differently(New York,NY)

order of severity:
completness<validity<accurcy,

steps involve in data cleaning

define,code,test

In [39]:
#replacing null values
patient.fillna("no data",inplace=True)

<ipython-input-39-10431374b3a2>:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'no data' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  patient.fillna("no data",inplace=True)

In [40]:
treatment['hba1c_change']=treatment['hba1c_start']-treatment['hba1c_end']
treatment_cut['hba1c_change']=treatment_cut['hba1c_start']-treatment_cut['hba1c_end']

In [41]:
treatment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    280 non-null    object
 1   surname       280 non-null    object
 2   auralin       280 non-null    object
 3   novodra       280 non-null    object
 4   hba1c_start   280 non-null    float64
 5   hba1c_end     280 non-null    float64
 6   hba1c_change  280 non-null    float64
dtypes: float64(3), object(4)
memory usage: 15.4+ KB

In [42]:
#as in some mail is ahead and in som e the number is ahesad therefore use reg x
patient['contact']

0                 951-719-9170ZoeWellish@superrito.com
1                PamelaSHill@cuvox.de+1 (217) 569-3204
2                     402-363-6804JaeMDebord@gustr.com
3           PhanBaLiem@jourrapide.com+1 (732) 636-8246
4                      334-515-7487TimNeudorf@cuvox.de
                            ...
498        207-477-0579MustafaLindstrom@jourrapide.com
499                 928-284-4492RumanBisliev@gustr.com
500              816-223-6007JinkedeKeizer@teleworm.us
501    ChidaluOnyekaozulu@jourrapide.com1 360 443 2060
502               PatrickGersten@rhyta.com402-848-4923
Name: contact, Length: 503, dtype: object

In [43]:
import re

def find_contact_details(text: str) -> tuple:
    # it the value is NaN, then return it
    if pd.isna(text):
        return np.nan

    # create the phone number pattern
    phone_number_pattern = re.compile(r"(\+[\d]{1,3}\s)?(\(?[\d]{3}\)?\s?-?[\d]{3}\s?-?[\d]{4})")
    # find the phone number from the value/text, as a result we will get a list
    phone_number  = re.findall(phone_number_pattern, text)

    # if length is 0, then the regex can't find any ph number, then define with NaN
    if len(phone_number) <= 0:
        phone_number = np.nan
    # if the country code is attached with the ph number, for that case, the first
    # element will be the country code and the 2nd element will be the actual ph
    # number. So, get that ph number
    elif len(phone_number) >= 2:
        phone_number = phone_number[1]
    # else, we will get the ph number. Grab it.
    else:
        phone_number = phone_number[0]

    # if we found the ph number (with/without country code), then remove that part from the actual value.
    # after removing the ph number, the remaining string might be the email address.
    possible_email_add = re.sub(phone_number_pattern, "", text).strip()

    # then return the ph number and the email address
    return phone_number, possible_email_add

In [44]:
patient['phone']=patient['contact'].apply(lambda x: find_contact_details(x)).apply(lambda x:x[0])
patient['email']=patient["contact"].apply(lambda x: find_contact_details(x)).apply(lambda x:x[1])

In [45]:
patient.drop(columns=['contact'],inplace=True)

In [46]:
patient.head(4)

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,birthdate,weight,height,bmi,phone,email
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,7/10/1976,121.7,66,19.6,"(, 951-719-9170)",ZoeWellish@superrito.com
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,4/3/1967,118.8,66,19.2,"(+1 , (217) 569-3204)",PamelaSHill@cuvox.de
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,2/19/1980,177.8,71,24.8,"(, 402-363-6804)",JaeMDebord@gustr.com
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,7/26/1951,220.9,70,31.7,"(+1 , (732) 636-8246)",PhanBaLiem@jourrapide.com

In [47]:
treatment=pd.concat([treatment,treatment_cut])

In [48]:
treatment

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,0.43
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.47
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,0.43
3,skye,gormanston,33u - 36u,-,7.97,7.62,0.35
4,alissa,montez,-,33u - 29u,7.78,7.46,0.32
...,...,...,...,...,...,...,...
65,rovzan,kishiev,32u - 37u,-,7.75,7.41,0.34
66,jakob,jakobsen,-,28u - 26u,7.96,7.51,0.45
67,bernd,schneider,48u - 56u,-,7.74,7.44,0.30
68,berta,napolitani,-,42u - 44u,7.68,7.21,0.47
69,armina,sauvé,36u - 46u,-,7.86,7.40,0.46

In [49]:
treatment=treatment.melt(id_vars=['given_name',	'surname',	'hba1c_start',	'hba1c_end',	'hba1c_change'],var_name='type',value_name='dosage_name')

In [50]:
treatment=treatment[treatment['dosage_name']!='-']

In [51]:
treatment['dosage_start']=treatment['dosage_name'].str.split('-').str.get(0)

In [52]:
treatment['dosage_end']=treatment['dosage_name'].str.split('-').str.get(1)

In [53]:
treatment.drop(columns=['dosage_name'],inplace=True)

In [54]:
treatment['dosage_start']=treatment['dosage_start'].str.replace('u','')

In [55]:
treatment['dosage_end']=treatment['dosage_end'].str.replace('u','')

In [56]:
treatment['dosage_start']=treatment['dosage_start'].astype('int')
treatment['dosage_end']=treatment['dosage_end'].astype('int')

In [57]:
treatment=treatment.merge(adverse,how='left',on=['given_name','surname'])

In [58]:
treatment.fillna('no reaction',inplace=True)

In [59]:
treatment

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,dosage_start,dosage_end,adverse_reaction
0,veronika,jindrová,7.63,7.20,0.43,auralin,41,48,no reaction
1,skye,gormanston,7.97,7.62,0.35,auralin,33,36,no reaction
2,sophia,haugen,7.65,7.27,0.38,auralin,37,42,no reaction
3,eddie,archer,7.89,7.55,0.34,auralin,31,38,no reaction
4,asia,woźniak,7.76,7.37,0.39,auralin,30,36,no reaction
...,...,...,...,...,...,...,...,...,...
345,christopher,woodward,7.51,7.06,0.45,novodra,55,51,nausea
346,maret,sultygov,7.67,7.30,0.37,novodra,26,23,no reaction
347,lixue,hsueh,9.21,8.80,0.41,novodra,22,23,injection site discomfort
348,jakob,jakobsen,7.96,7.51,0.45,novodra,28,26,hypoglycemia
349,berta,napolitani,7.68,7.21,0.47,novodra,42,44,injection site discomfort